language: java
jdk:
  - openjdk8

branches:
  only:
    - main #오직 main 브랜치에서 push 될때만

# Travis CI 서버의 Home
#Gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포때부터 다시 받지 않도록 설정합니다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'


#master 브랜치에 PUSH 되었을때 수행하는 명령어입니다.
#여기선 프로젝트 내부에 둔 gradlew을 통해 clean & build 를 수행합니다
before_install:
  - chmod +x gradlew
script:
  - ./gradlew clean build

before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot2-webservice.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis Repo에 설정된값
    secret_access_key: $AWS_SECRET_KEY

    bucket: springboot-webservice-deploy #만들어놓은 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true



# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - qkrtprjs456@gmail.com


#travis 확인7